### ISSUE TITLE
Support for typeof expression

### ISSUE THREAD

**Issue by hauke725** [ctxkiwi/vue-pre#5]
Vue has no problem parsing this expression:
`typeof var.test !== 'undefined' && var.test > 0`
When I try the same thing with vue-pre I get:
`Error: VuePre doesnt understand this JS expression: "typeof var.test && var.test > 0"`
When leaving out the typeof check it shows this error:
`Error: Cant parse "\VuePre\ConvertJsExpression::getObjectValue($var, ['test'])" : Undefined index: test`

**Comment by ctxkiwi** [comment]
so, typeof isnt supported yet. But i see this is indeed a problem. I will fix this as soon as i can.

**Comment by ctxkiwi** [comment]
This is now fixed, note: you must use () brackets when using typeof
e.g. typeof(var.test)

**Comment by hauke725** [comment]
That was quick, thank you!

Lorenz Vandevelde <notifications@github.com> schrieb am Mo., 6. Mai 2019,
14:30:

**Comment by ctxkiwi** [comment]
> That was quick, thank you! 

It wasn't quick at all... I only saw your issue after like 13 days. I feel kinda bad for that 😅
